incus-jenkins: retry ssh-keyscan

diff --git a/tests/nx-2556/Makefile b/tests/nx-2556/Makefile
--- a/tests/nx-2556/Makefile
+++ b/tests/nx-2556/Makefile
@@ -108,7 +108,8 @@ ${VM_NAME}.access.configured: ${VM_NAME}.created ssh_key
 
 	incus exec ${VM_NAME} -- apt install -y openssh-server
 	# Ubuntu automatically enables the service, it is named `sshd` in systemd.
-	ssh-keyscan -H `cat $(VM_NAME).ipv4` > ${VM_NAME}.known_hosts
+	# There might be a delay until port 22 accepts connections, hence loop. See build 4, 5 failure.
+	while ! ssh-keyscan -H `cat $(VM_NAME).ipv4` > ${VM_NAME}.known_hosts; do echo -n .; sleep 1; done
 
 	echo "Host ${VM_NAME} `cat $(VM_NAME).ipv4`"            > ${VM_NAME}.ssh_config
 	echo "  Hostname `cat $(VM_NAME).ipv4`"                >> ${VM_NAME}.ssh_config
