reformat

diff --git a/packages/solaris/server/files/netxmsd b/packages/solaris/server/files/netxmsd
--- a/packages/solaris/server/files/netxmsd
+++ b/packages/solaris/server/files/netxmsd
@@ -9,8 +9,8 @@
 # to use the same script.
 
 getproparg() {
-        val=`svcprop -p $1 $SMF_FMRI`
-        [ -n "$val" ] && echo $val
+    val=`svcprop -p $1 $SMF_FMRI`
+    [ -n "$val" ] && echo $val
 }
 
 NXBIN=`getproparg netxms/bin`
@@ -20,35 +20,35 @@ DEBUGLEVEL=`getproparg netxms/server_debuglevel`
 ARGS=
 
 if [ -f $NXBIN/nxenv ]; then
-	. $NXBIN/nxenv
+    . $NXBIN/nxenv
 fi
 
 if [ -z $SMF_FMRI ]; then
-	echo "Error: SMF framework variables are not initialized"
-	exit $SMF_EXIT_ERR
+    echo "Error: SMF framework variables are not initialized"
+    exit $SMF_EXIT_ERR
 fi
 
 if [ x"$CONFIGFILE" != "x" ]; then
-	ARGS=$ARGS -c \"$CONFIGFILE\"
+    ARGS=$ARGS -c \"$CONFIGFILE\"
 fi
 
 if [ x"$DEBUGLEVEL" != "x" ]; then
-	ARGS=$ARGS -D $DEBUGLEVEL
+    ARGS=$ARGS -D $DEBUGLEVEL
 fi
 
 case "$1" in
-'start')
-	$NXBIN/netxmsd -d $ARGS
+    'start')
+        $NXBIN/netxmsd -d $ARGS
         ;;
 
-'stop')
-	pkill netxmsd
+    'stop')
+        pkill netxmsd
         ;;
 
-*)
+    *)
         echo "Usage: $0 {start|stop}"
         exit 1
         ;;
-
 esac
+
 exit $SMF_EXIT_OK
