Fixed: solaris startup script failed when config or debug level is set

diff --git a/packages/solaris/server/files/netxmsd b/packages/solaris/server/files/netxmsd
--- a/packages/solaris/server/files/netxmsd
+++ b/packages/solaris/server/files/netxmsd
@@ -5,8 +5,10 @@
 
 . /lib/svc/share/smf_include.sh
 
-# SMF_FMRI is the name of the target service. This allows multiple instances 
-# to use the same script.
+if [ -z $SMF_FMRI ]; then
+    echo "Error: SMF framework variables are not initialized"
+    exit $SMF_EXIT_ERR
+fi
 
 getproparg() {
     val=`svcprop -p $1 $SMF_FMRI`
@@ -23,17 +25,12 @@ if [ -f $NXBIN/nxenv ]; then
     . $NXBIN/nxenv
 fi
 
-if [ -z $SMF_FMRI ]; then
-    echo "Error: SMF framework variables are not initialized"
-    exit $SMF_EXIT_ERR
-fi
-
 if [ x"$CONFIGFILE" != "x" ]; then
-    ARGS=$ARGS -c \"$CONFIGFILE\"
+    ARGS="$ARGS -c \"$CONFIGFILE\""
 fi
 
 if [ x"$DEBUGLEVEL" != "x" ]; then
-    ARGS=$ARGS -D $DEBUGLEVEL
+    ARGS="$ARGS -D $DEBUGLEVEL"
 fi
 
 case "$1" in
